apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  namespace: case-study
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/mysql

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: migrations
  namespace: case-study
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /migrations