apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: case-study
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migrations
  namespace: case-study
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi